### ISSUE TITLE
Expanded encoder doesn't encode colon character

### ISSUE THREAD

**Issue by Timberjaw** [threedaymonk/htmlentities#24] opened 2015-07-20 23:20 UTC
Not sure if this is by design, but the expanded encoder (which includes a mapping for the colon character) doesn't convert colons to their HTML entity form. The use case is encoding title text for use in a YAML front matter block (and subsequently embedding in an HTML page).

My code:

    require 'htmlentities'
    title = "Foo: Bar"
    coder = HTMLEntities.new(:expanded)
    coder.encode(title, :hexadecimal)

Expected: "Foo\&#58; Bar"
Got: "Foo: Bar"

Also tried coder.encode(title, :decimal), coder.encode(title, :named, :decimal), and coder.encode(title). Tested with IRB to make sure the problem isn't coming from somewhere else.

**Comment by Timberjaw** [comment] 2015-07-20 23:35
Using gsub as a workaround for now.

**Comment by threedaymonk** [comment] 2015-07-21 08:46
This is by design: it's only intended to encode characters which

1. have a special meaning in HTML/XML/SGML; or
2. (optionally) are outside the ASCII range.

Encoding YAML is definitely out of scope.

**Closed by threedaymonk** 2015-07-21 08:46 UTC
